# Generated by Django 6.0.3 on 2026-03-19 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_officer_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officer',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
