# Generated by Django 6.0.3 on 2026-04-27 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_galleryimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryimage',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
