# Generated by Django 6.0.3 on 2026-04-29 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_rename_name_contactmessage_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='officer',
            name='instagram',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='officer',
            name='linkedIn',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
